name: testing_app
description: A sample that shows testing in Flutter.

version: 1.0.0+1

environment:
  sdk: ">=2.17.0-0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3
  provider: ^6.0.2
  go_router: ^6.0.0

dev_dependencies:
  analysis_defaults:
    path: ../analysis_defaults
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  test: ^1.16.8
  http: ^0.13.0

flutter:
  uses-material-design: true
